---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap-instance-day2
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: aap-instance
    app.kubernetes.io/part-of: ansible-automation-platform
    deployment-phase: day-2
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: ansible-automation-platform
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/aap-instance
    repoURL: https://github.com/hultzj/aap-policy.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        # Basic AAP Configuration
        - name: aap.name
          value: "aap-controller"
        - name: aap.namespace
          value: "ansible-automation-platform"
        - name: aap.version
          value: "2.5"
        # Admin Configuration
        - name: aap.admin.username
          value: "admin"
        - name: aap.admin.email
          value: "admin@example.com"
        # License Configuration (REQUIRED - set enabled=true and provide content)
        - name: aap.license.enabled
          value: "false"
        - name: aap.license.secretName
          value: "aap-license"
        - name: aap.license.content
          value: ""  # Base64 encoded license JSON content
        # Resource Configuration
        - name: aap.resources.cpu
          value: "1000m"
        - name: aap.resources.memory
          value: "2Gi"
        # Storage Configuration
        - name: aap.storage.size
          value: "20Gi"
        # Database Configuration (external postgres optional)
        - name: aap.database.external.enabled
          value: "false"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 3
  ignoreDifferences:
    - group: automationcontroller.ansible.com
      kind: AutomationController
      jsonPointers:
        - /status
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap-servicemesh-day2
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: aap-servicemesh
    app.kubernetes.io/part-of: ansible-automation-platform
    deployment-phase: day-2
    optional: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    namespace: ansible-automation-platform
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/aap-servicemesh
    repoURL: https://github.com/hultzj/aap-policy.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: serviceMesh.enabled
          value: "false"
        - name: serviceMesh.istio.enabled
          value: "false"
        - name: serviceMesh.ossm.enabled
          value: "false"
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
