apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operator.operatorGroup.name }}
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- toYaml .Values.operator.labels | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    {{- toYaml .Values.operator.operatorGroup.targetNamespaces | nindent 4 }}
