{{- if .Values.aapInstance.postgres.external.enabled }}
{{- if not .Values.aapInstance.postgres.external.secretName }}
# External Postgres Secret for AutomationController
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aapInstance.name }}-postgres-configuration
  namespace: {{ .Values.aapInstance.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.aapInstance.name }}
    app.kubernetes.io/part-of: ansible-automation-platform
    app.kubernetes.io/managed-by: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  host: {{ .Values.aapInstance.postgres.external.host | quote }}
  port: {{ .Values.aapInstance.postgres.external.port | quote }}
  database: {{ .Values.aapInstance.postgres.external.database | quote }}
  username: {{ .Values.aapInstance.postgres.external.username | quote }}
  password: {{ .Values.aapInstance.postgres.external.password | quote }}
  sslmode: {{ .Values.aapInstance.postgres.external.sslMode | quote }}
  type: managed
---
{{- end }}
{{- end }}

{{- if and .Values.automationHub.enabled .Values.automationHub.postgres.external.enabled }}
{{- if not .Values.automationHub.postgres.external.secretName }}
# External Postgres Secret for AutomationHub
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.automationHub.name }}-postgres-configuration
  namespace: {{ .Values.automationHub.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.automationHub.name }}
    app.kubernetes.io/part-of: ansible-automation-platform
    app.kubernetes.io/managed-by: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  host: {{ .Values.automationHub.postgres.external.host | quote }}
  port: {{ .Values.automationHub.postgres.external.port | quote }}
  database: {{ .Values.automationHub.postgres.external.database | quote }}
  username: {{ .Values.automationHub.postgres.external.username | quote }}
  password: {{ .Values.automationHub.postgres.external.password | quote }}
  sslmode: {{ .Values.automationHub.postgres.external.sslMode | quote }}
  type: managed
---
{{- end }}
{{- end }}

{{- if and .Values.edaController.enabled .Values.edaController.postgres.external.enabled }}
{{- if not .Values.edaController.postgres.external.secretName }}
# External Postgres Secret for EDAController
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.edaController.name }}-postgres-configuration
  namespace: {{ .Values.edaController.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.edaController.name }}
    app.kubernetes.io/part-of: ansible-automation-platform
    app.kubernetes.io/managed-by: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  host: {{ .Values.edaController.postgres.external.host | quote }}
  port: {{ .Values.edaController.postgres.external.port | quote }}
  database: {{ .Values.edaController.postgres.external.database | quote }}
  username: {{ .Values.edaController.postgres.external.username | quote }}
  password: {{ .Values.edaController.postgres.external.password | quote }}
  sslmode: {{ .Values.edaController.postgres.external.sslMode | quote }}
  type: managed
---
{{- end }}
{{- end }}
