{{- if .Values.aap.database.external.enabled }}
{{- if not .Values.aap.database.external.secretName }}
# External Postgres Secret for AutomationController
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aap.name }}-postgres-configuration
  namespace: {{ .Values.aap.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.aap.name }}
    app.kubernetes.io/part-of: ansible-automation-platform
    app.kubernetes.io/managed-by: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  host: {{ .Values.aap.database.external.host | quote }}
  port: {{ .Values.aap.database.external.port | quote }}
  database: {{ .Values.aap.database.external.database | quote }}
  username: {{ .Values.aap.database.external.username | quote }}
  password: {{ .Values.aap.database.external.password | quote }}
  sslmode: "prefer"
  type: managed
---
{{- end }}
{{- end }}
